export const styles = {
  container: {
    padding: '20px',
    fontFamily: "'Playfair Display', serif", 
  },
  pageTitle: {
    textAlign: 'center',
    fontSize: '2.5rem',
    marginBottom: '30px',
    fontWeight: 'normal',
  },
  toggleContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '40px',
    marginBottom: '40px',
  },
  toggleBtn: {
    padding: '10px 40px',
    borderRadius: '30px',
    border: 'none',
    backgroundColor: '#e0dccb', 
    fontSize: '1.2rem',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  toggleBtnActive: {
    padding: '10px 40px',
    borderRadius: '30px',
    border: 'none',
    backgroundColor: '#7a9a7a', 
    color: 'white',
    fontSize: '1.2rem',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  tabContent: {
    display: 'flex',
    gap: '40px',
  },
  actionArea: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    minWidth: '150px',
    alignItems: 'center',
  },
  addButtonContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '5px',
  },
  addLabel: {
    fontSize: '0.9rem',
    color: '#333',
  },
  plusButton: {
    width: '60px',
    height: '60px',
    borderRadius: '12px',
    backgroundColor: '#7a9a7a', 
    color: 'white',
    fontSize: '2rem',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
  },
  plusButtonBrown: {
    width: '60px',
    height: '60px',
    borderRadius: '12px',
    backgroundColor: '#8b7e66', 
    color: 'white',
    fontSize: '2rem',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
  },
  tableCard: {
    flex: 1,
    backgroundColor: '#fff', 
    borderRadius: '15px',
    padding: '20px',
    boxShadow: '0 4px 10px rgba(0,0,0,0.05)',
    minHeight: '400px',
  },
  tableHeaderRow: {
    display: 'flex',
    borderBottom: '1px solid #eee',
    paddingBottom: '10px',
    marginBottom: '10px',
    fontWeight: 'bold',
    color: '#555',
    fontFamily: 'sans-serif',
  },
  tableRow: {
    display: 'flex',
    padding: '12px 0',
    borderBottom: '1px solid #f9f9f9',
    alignItems: 'center',
    fontFamily: 'sans-serif',
    fontSize: '1.1rem',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  col: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  tablesGrid: {
    flex: 1,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '20px',
  },
  seatCard: {
    backgroundColor: '#fdfbf7',
    borderRadius: '10px',
    padding: '15px',
    boxShadow: '0 2px 5px rgba(0,0,0,0.05)',
    border: '1px solid #eee',
    cursor: 'pointer',
    transition: 'transform 0.2s',
  },
  seatHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '10px',
    borderBottom: '1px solid #e0dccb',
    paddingBottom: '5px',
  },
  seatTitle: {
    fontWeight: 'bold',
    color: '#555',
    fontSize: '1.1rem',
  },
  seatCount: {
    fontWeight: 'bold',
    color: '#333',
  },
  seatList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  seatItem: {
    fontSize: '1rem',
    color: '#444',
  },
  deleteTableBtn: {
    marginTop: '10px',
    fontSize: '0.8rem',
    color: 'red',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    textDecoration: 'underline',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '10px',
    width: '350px',
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  input: {
    padding: '10px',
    borderRadius: '5px',
    border: '1px solid #ccc',
    fontSize: '1rem',
    width: '100%',
    boxSizing: 'border-box',
  },
  label: {
    fontSize: '0.9rem',
    fontWeight: 'bold',
    marginBottom: '-10px',
    color: '#555',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    marginTop: '10px',
  },
  saveBtn: {
    padding: '10px 20px',
    backgroundColor: '#7a9a7a',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '1rem',
  },
  cancelBtn: {
    padding: '10px 20px',
    backgroundColor: '#ccc',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '1rem',
  },
  closeX: {
    background: 'none',
    border: 'none',
    fontSize: '1.5rem',
    cursor: 'pointer',
    color: '#888',
  },
  guestListScroll: {
    maxHeight: '200px',
    overflowY: 'auto',
    border: '1px solid #eee',
    padding: '10px',
    borderRadius: '5px',
  },
  guestRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '5px 0',
    borderBottom: '1px solid #f9f9f9',
  },
  removeBtn: {
    background: '#ffcccc',
    color: 'red',
    border: 'none',
    borderRadius: '50%',
    width: '24px',
    height: '24px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  addGuestToTableBtn: {
    backgroundColor: '#7a9a7a',
    color: 'white',
    border: 'none',
    padding: '8px 15px',
    borderRadius: '20px',
    cursor: 'pointer',
  },
  assignBtn: {
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    padding: '5px 10px',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  editBtn: {
    backgroundColor: '#ffa500',
    color: 'white',
    border: 'none',
    padding: '8px 15px',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  statsCard: {
    minWidth: 220,
    background: 'linear-gradient(180deg,#fff,#fbfbf7)',
    borderRadius: 12,
    padding: 12,
    boxShadow: '0 2px 6px rgba(0,0,0,0.05)',
    border: '1px solid #eee',
    fontSize: '0.95rem',
    color: '#333'
  },
  smallInput: {
    padding: '6px 8px',
    borderRadius: 6,
    border: '1px solid #ccc',
    width: 80,
  },
  smallSaveBtn: {
    padding: '6px 10px',
    borderRadius: 6,
    border: 'none',
    backgroundColor: '#7a9a7a',
    color: 'white',
    cursor: 'pointer'
  }
};
